### ISSUE TITLE
Не подгружает стили и скрипты DLE 11

### ISSUE THREAD

**Issue by dimcka42** [dle-modules/DLE-Asset#2]
Не подгружает стили и скрипты DLE 11. Всё сделано по инструкции. Возможно с чем-то конфликтует, но не могу понять с чем. Путь к папкам прописал свой, но никак:
{include file="engine/modules/asset/add.php?folder={THEME}/style/"}
{include file="engine/modules/asset/add.php?folder={THEME}/js/"}

**Comment by pafnuty** [comment]
Напишите адрес сайта.
