### ISSUE TITLE
на хотят работать js при включении модуля

### ISSUE THREAD

**Issue by frost-agb** [dle-modules/DLE-Asset#3]
---

@pafnuty не забудь посмотреть этот тиккет :ticket:
Здравствуйте вы мне дали ссылку, чтобы я написал тикет тут, так вот у меня как таковой ошибки нету, просто не запускаются js, на сайте есть кнопка кнопка "показать еще" перестаёт работать, верхний слайдер, видео проигрователь....
Только что осинило, чувство такое что не работают только те скрипты которые встроены в шаблон `<script>...</script>`, ну то есть код скрипта прописан в шаблоне а не в отдельном файле в папке с js.

**Comment by pafnuty** [comment]
Добрый день.
Пришлите ссылку на сайт с ошибкой.

26 сентября 2016 г., 1:18 пользователь frost-agb notifications@github.com
написал:

**Comment by frost-agb** [comment]
Ссылку на сайт я скидывал в личку вам на `http://dle-faq.ru/`. Просто не хочу светить адресом.

```
index.php:76 Uncaught SyntaxError: Unexpected token <
(index):2566 Uncaught TypeError: $(...).flexslider is not a function
```

это 2 ошибки появляются в хроме "f12", когда подключаю
`{include file="engine/modules/asset/add.php?folder={THEME}/js/"}`

побывал скрипты которые прописаны в шаблоне `<script>...</script>`, выносить в файл и подключать, через `{include file="engine/modules/asset/addFile.php?file={THEME}/js/скрипт.js"}`.
Если правильно понимаю то этот тег, надо вставить туда, где был прописан в шаблоне `<script>...</script>`, вместо него.

**Comment by pafnuty** [comment]
Сейчас на сайте ошибки нет.

**Comment by frost-agb** [comment]
{include file="engine/modules/asset/add.php?folder={THEME}/js/"} убрал, так как с ним сайт не работает. Можно с вами как то связаться в скайпе или еще где?
чтобы попробовать решить эту проблему онлайн. Могу дать доступ к сайту.
